#pragma once

using namespace ATL;

template <class T>
class CProxy_IVideoEncoderEvents : public IConnectionPointImpl<T, &__uuidof( _IVideoEncoderEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
