// MusicianHelperNativeVideoEncoder.idl : IDL source for MusicianHelper.NativeVideoEncoder
//

// This file will be processed by the MIDL tool to
// produce the type library (MusicianHelperNativeVideoEncoder.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(44E702F5-BDD4-4ADB-A21E-3450E3EED6FE),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IVideoEncoderWrapper : IDispatch{
    [propget, id(1)] HRESULT ImageFilePath([out, retval] LPCWSTR* pVal);
    [propput, id(1)] HRESULT ImageFilePath([in] LPCWSTR newVal);
};
[
	uuid(351A3835-16A2-4D7B-A51A-9E6FC4A5D20B),
	version(1.0),
]
library MusicianHelperNativeVideoEncoderLib
{
	importlib("stdole2.tlb");
	[
		uuid(7AC47479-9A6A-4A44-AD88-3C756802DBBA)		
	]
	coclass VideoEncoderWrapper
	{
		[default] interface IVideoEncoderWrapper;
	};
};

